from: markdown+superscript
to: pdf

output-file: "docs/General Documentation.pdf"
input-files:
  - source/general/Title.md
  - source/general/Theoretical.md
  - source/general/AcqKnowledge.md
  - source/general/Acq2Bva.md
  - source/general/BrainVisionAnalyzer.md

include-in-header:
  - disable_float.tex

variables:
  block-headings: true
  documentclass: scrreprt
  geometry:
    - margin=1in
  linestretch: 1.5
  papersize: a4
  margin: 1in
  toc: true
  toc-depth: 4
  numbersections: true
  secnumdepth: 1
