from: markdown+superscript
to: pdf

output-file: "docs/Present Study - Setup and Analysis.pdf"
input-files:
  - source/present/Title.md
  - source/present/AcqKnowledge.md
  - source/present/Acq2Bva.md
  - source/present/BrainVisionAnalyzer.md
  - source/present/DataAnalysis.md

include-in-header:
  - disable_float.tex

variables:
  block-headings: true
  documentclass: scrreprt
  geometry:
    - margin=1in
  linestretch: 1.5
  papersize: a4
  margin: 1in
  toc: true
  toc-depth: 4
  numbersections: true
  secnumdepth: 1
