from: markdown+superscript
to: pdf

output-file: "docs/Present Study - Instructions.pdf"
input-files:
  - source/present_instructions/Title.md
  - source/present_instructions/EquipmentOverview.md
  - source/present_instructions/Preparation.md

include-in-header:
  - disable_float.tex

variables:
  block-headings: true
  documentclass: scrreprt
  geometry:
    - margin=1in
  linestretch: 1.5
  papersize: a4
  margin: 1in
  toc: true
  toc-depth: 4
  numbersections: true
  secnumdepth: 1
